{% set name = "sphinxcontrib-jquery" %}
{% set version = "4.0" %}
{% set sha256 = "3fb0bf3c8906d873a817fe5a6b15b4d3453356c5a86939e0c64c38c0ef08b7a9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=2.7
    - pip
    - flit-core >=3.7,<4
  run:
    - python >=2.7
    - sphinx >=1.8

test:
  imports:
    - sphinxcontrib.jquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinxcontrib-jquery/
  license: 0BSD AND MIT
  license_file:
#    - LICENCE
    - vendor-licenses/
  summary: A sphinx extension to include jQuery on newer sphinx releases
  description: |
    sphinxcontrib-jquery ensures that jQuery is always installed for use in
    Sphinx themes or extensions.
  dev_url: https://github.com/sphinx-contrib/jquery

extra:
  recipe-maintainers:
    - AA-Turner
    - BSGalvan
